### ISSUE TITLE
sincerely request for data file 'gpr_medium.mat'

### ISSUE THREAD

**Issue by WangZiNi** [CL2-UWaterloo/GP-MPC-of-Platooning#2]
Dear author,
I am writing to request access to your data. I am very interested in your work and would like to use your data for my own research. I would be extremely grateful if you could provide me with the data file 'gpr_medium.mat'. 
Thank you very much for considering my request, and I am looking forward to your reply.
Sincerely, Zini Wang

**Comment by jwangjie** [comment]
Hi ZiNi, 

Thanks for your interest in our work. You can access the trained GP model at [here](https://drive.google.com/file/d/14UYLP5DWKnFuQayjXLaNjMgmxGEYJsOu/view?usp=sharing).

Regards,
Jie

**Comment by WangZiNi** [comment]
I am so glad to get your reply and help, hope everything goes well with you, sincerely.




W
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "CL2-UWaterloo/GP-MPC-of-Platooning"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月7日(星期三) 晚上9:43
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [CL2-UWaterloo/GP-MPC-of-Platooning] sincerely request for data file 'gpr_medium.mat' (Issue #2)





 
Hi ZiNi,
 
Thanks for your interest in our work. You can access the trained GP model at here.
 
Regards,
 Jie

**Comment by Bubblefn** [comment]
Dear author,
     `GP_MPC_Platoon_simulation`
    When I ran this file, I encountered the following error, and the simulation could not stop. Have you ever encountered this problem?
CasADi - 2024-04-04 17:33:08 WARNING("solver:nlp_jac_g failed: Inf detected for output jac_g_x, at nonzero index 357 (row 18, col 108).") [.../casadi/core/oracle_function.cpp:377]
Error evaluating Jacobian of equality constraints at user provided starting point.
  No scaling factors for equality constraints computed!

**Comment by jwangjie** [comment]
> Dear author, `GP_MPC_Platoon_simulation` When I ran this file, I encountered the following error, and the simulation could not stop. Have you ever encountered this problem? CasADi - 2024-04-04 17:33:08 WARNING("solver:nlp_jac_g failed: Inf detected for output jac_g_x, at nonzero index 357 (row 18, col 108).") [.../casadi/core/oracle_function.cpp:377] Error evaluating Jacobian of equality constraints at user provided starting point. No scaling factors for equality constraints computed!

You can try to change [`'max_iter', 100`](https://github.com/CL2-UWaterloo/GP-MPC-of-Platooning/blob/6811f897403f1fe16d847abdb491bdf5e7155dcf/GP_ARX_simulation/GP_MPC_platoon.m#L258C75-L258C91) to `30` to alleviate this issue.

**Comment by Bubblefn** [comment]
> > Dear author, `GP_MPC_Platoon_simulation` When I ran this file, I encountered the following error, and the simulation could not stop. Have you ever encountered this problem? CasADi - 2024-04-04 17:33:08 WARNING("solver:nlp_jac_g failed: Inf detected for output jac_g_x, at nonzero index 357 (row 18, col 108).") [.../casadi/core/oracle_function.cpp:377] Error evaluating Jacobian of equality constraints at user provided starting point. No scaling factors for equality constraints computed!
> 
> You can try to change [`'max_iter', 100`](https://github.com/CL2-UWaterloo/GP-MPC-of-Platooning/blob/6811f897403f1fe16d847abdb491bdf5e7155dcf/GP_ARX_simulation/GP_MPC_platoon.m#L258C75-L258C91) to `30` to alleviate this issue.

The problem still exists. Why is it shown that scale factors without calculated equality constraints are displayed? Do you know the reason?
CasADi - 2024-04-12 14:25:55 WARNING("solver:nlp_jac_g failed: Inf detected for output jac_g_x, at nonzero index 357 (row 18, col 108).") [.../casadi/core/oracle_function.cpp:377]
Error evaluating Jacobian of equality constraints at user provided starting point.
  No scaling factors for equality constraints computed!
CasADi - 2024-04-12 14:25:55 WARNING("solver:nlp_jac_g failed: Inf detected for output jac_g_x, at nonzero index 357 (row 18, col 108).") [.../casadi/core/oracle_function.cpp:377]
Error evaluating Jacobian of inequality constraints at user provided starting point.
  No scaling factors for inequality constraints computed!
